apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "greet-app-chart.fullname" . }}-monitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
    - port: http  # we'll define this port name in service.yaml below
      path: /metrics
      interval: 30s
